plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

preferInteractive: true
pnpEnableEsmLoader: true

supportedArchitectures:
  os:
    - "darwin"
    - "linux"
    - "win32"

  cpu:
    - "x86"
    - "x64"
    - "arm64"
# Uncomment line below if we need to support 32-bit architectures at build time
#    - "ia32"

npmScopes:
  # Ensure that no @demo/* packages can be accidentally installed from npmjs.com
  demo:
    npmRegistryServer: https://127.0.0.1

yarnPath: .yarn/releases/yarn-3.6.2.cjs

packageExtensions:
  # Chalk has some funky imports with a hashtag as prefix
  # https://github.com/chalk/chalk/issues/531
  "chalk@*":
    dependencies:
      "#ansi-styles": "npm:ansi-styles@*"
      "#supports-color": "npm:supports-color@*"
  "local-pkg@*":
    peerDependencies:
      "jsdom": "*"
  "babel-plugin-relay@*":
    dependencies:
      "@babel/runtime": "*"
  "@playwright/experimental-ct-react@*":
    dependencies:
      "@playwright/test": "*"
      "vite": "*"
  "@playwright/experimental-ct-core@*":
    dependencies:
      "playwright-core": "*"
